plugins {
    id 'com.android.application'
}

android {
    namespace 'com.maple.daily'
    compileSdk 34

    defaultConfig {
        applicationId 'com.maple.daily'
        minSdk 23
        targetSdk 34
        versionCode 13
        versionName '0.9.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

def buildDate = new Date().format('yyyyMMdd')

android.applicationVariants.configureEach { variant ->
    def apkFileName = "Daily-${variant.versionName}-${buildDate}.apk"

    variant.outputs.configureEach {
        outputFileName = apkFileName
    }

    if (variant.name == 'debug') {
        def archiveTaskName = "archive${variant.name.capitalize()}Apk"
        tasks.register(archiveTaskName, Copy) {
            from("${buildDir}/outputs/apk/${variant.name}") {
                include apkFileName
            }
            into("${rootDir}/release-apks")
        }

        tasks.named("assemble${variant.name.capitalize()}").configure {
            finalizedBy archiveTaskName
        }
    }
}
