plugins {
    id 'com.android.application'
}

android {
    namespace 'com.maple.daily'
    compileSdk 34

    defaultConfig {
        applicationId 'com.maple.daily'
        minSdk 23
        targetSdk 34
        versionCode 6
        versionName '0.5.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

def buildDate = new Date().format('yyyyMMdd')

android.applicationVariants.configureEach { variant ->
    variant.outputs.configureEach {
        outputFileName = "Daily-${variant.versionName}-${buildDate}.apk"
    }
}
